### PR TITLE
GHA docker publish pipeline

### PR DESCRIPTION
**Pull request by hiddenmarten**

### CODE REVIEW

**Review by AlexGluck — CHANGES_REQUESTED** [review]
Used version ubuntu must be fixed, example 22.04 not latest. When release new version ubuntu behaviour can be change and functionality ci will be broken.

**Review by AlexGluck — COMMENTED** [review]
Image tags set latest, how users can find correct version? May be we can add calver in iso8601 format? Add git hash short and full commit hash? Semver? Mixed variations?

**Comment by hiddenmarten** [comment]
Thanks for the suggestions, I appreciate it.
Keep in mind it's just a draft, it's not ready for review yet :)

**Comment by hiddenmarten** [comment]
Just took a GHA example and made some minor changes.

I think the `real` pipeline should be implemented after the discussion about versioning and all of this stuff.

**Review by kvaps — CHANGES_REQUESTED** [review]
@hiddenmarten pleaase make sure that pipeline works normally on other github repo.
You have to push changes to main, and try creating tag.

Eg. I tried to run it on https://github.com/kvaps/etcd-operator and https://github.com/kvaps/etcd-operator2 both didn't work

**Comment by hiddenmarten** [comment]
Now it works on my side:

https://github.com/hiddenmarten/etcd-operator/pkgs/container/etcd-operator

**Review by kvaps — APPROVED** [review]
From my side LGTM.

To reviewers: please use "Squash & Merge" for this PR

**Review by AlexGluck — APPROVED** [review]

**Pull request merged**
