### PR TITLE
add logging

### PR DESCRIPTION
**Pull request by oxxenix**
Fix https://github.com/aenix-io/etcd-operator/issues/177

### CODE REVIEW

**Review by kvaps — COMMENTED** [review]
Hey, let's omit all the 'was' and 'where' to make the text clearer and more concise.
I think this form is more common in Kubernetes ecosystem.

**Review by kvaps — APPROVED** [review]

**Comment by sergeyshevch** [comment]
Can we please check that all logs related to factories contains kind:EtcdCluster name/namespace?

**Review by sircthulhu — APPROVED** [review]
lgtm

**Comment by aobort** [comment]
> > Can we please check that all logs related to factories contains kind:EtcdCluster name/namespace?
> 
> 
> 
> As I understood it was not implemented yet @oxxenix ?

We're getting logger from request context which, afaik, already contain this info. And reconcileId as well.

**Review by sergeyshevch — APPROVED** [review]

**Pull request merged**
