### PR TITLE
Replace original PodSpec to corev1 PodSpec

### PR DESCRIPTION
**Pull request by Bo0km4n**
## Why
ref: #132 
These controllers create and update pod from template in crd. 
I think there is no reason wrap pod spec by original.

## What
- Use corev1 PodSpec
- Remove old PodSpec
- Fix tests

### CODE REVIEW

**Comment by gecube** [comment]
hello @Bo0km4n 

I think that we intentionally used our version of PodSpec. The ratio is that we don't want to allow user to change ANY field in PodSpec. Let's imagine very simple example. We have image field on EtcdCluster spec level. And we have image on PodSpec level. What if both will be set?

**Comment by Bo0km4n** [comment]
@gecube 
>I think that we intentionally used our version of PodSpec. 

I think there is no specific reason. please look #132 . 

> The ratio is that we don't want to allow user to change ANY field in PodSpec. 

What do you mean? 
It seems like implementation of etcdcluster webhook and controller don't restrict update pod spec of etcdcluster

>And we have image on PodSpec level. What if both will be set?

This commit just change PodSpec reference. etcdcluster have only one `image` filed, it is not duplicated.
I think this commit will not make breaking change for current user and resources.

**Comment by sergeyshevch** [comment]
@Bo0km4n Let's wait for #172. For now, opinions in the maintainers team are different and we created a proposal to discuss it in more detail

**Comment by lllamnyp** [comment]
This is done in #175.

**Pull request closed without merging**
