### PR TITLE
[43] Fix go vet hags on first run

### PR DESCRIPTION
**Pull request by hiddenmarten**

### CODE REVIEW

**Comment by sircthulhu** [comment]
@hiddenmarten 
Could you please explain why this change will fix this error?

**Comment by hiddenmarten** [comment]
@sircthulhu @sergeyshevch 

By default, pre-commit operates using multiple threads in parallel. However, this flag alters its behavior to use only one thread. I've tested this adjustment on my local setup and it helps.

**Review by AlexGluck — DISMISSED** [review]
I think we need change behavior instead of broke parallel work of linters (this worsens performance).

**Comment by genestack-okunitsyn** [comment]
> I think we need change behavior instead of broke parallel work of linters (this worsens performance).

Do you have any suggestions?

**Comment by hiddenmarten** [comment]
Probably I gave you an incorrect explanation about the behavior of pre-commit. 
I meant processes, not threads.

By default, pre-commit runs a bunch of processes
```
make-vet.................................................................Passed
- hook id: make-vet
- duration: 0.95s

go vet ./...
go vet ./...
go vet ./...
go vet ./...
go vet ./...
go vet ./...
go vet ./...
go vet ./...
go vet ./...
go vet ./...
go vet ./...
go vet ./...
go vet ./...
go vet ./...
go vet ./...
go vet ./...
go vet ./...
go vet ./...
```
however, with this option pre-commit runs `go vet ./...` only once, which means parallelization (as well as performance) of the linter itself isn't affected:

```
make-vet.................................................................Passed
- hook id: make-vet
- duration: 0.33s

go vet ./...

```

The root issue is about concurrent `go get .` calls triggered by `go vet ./...`.

**Review by gecube — APPROVED** [review]

**Review by AlexGluck — APPROVED** [review]
lgtm

**Pull request merged**
